import type { N8nWorkflow, WebhookNode } from '../n8n-api/types.js';
import { isWebhookNode } from '../n8n-api/types.js';

export function generateTypes(workflows: N8nWorkflow[]): string {
  const webhooks = workflows.flatMap((w) => extractWebhooks(w));

  const typeBlocks = webhooks.map((webhook) => generateWebhookTypes(webhook));

  if (typeBlocks.length === 0) {
    return `// Auto-generated by n8n-connect sync
// Do not edit manually

declare module '@n8n-connect/types' {
  export interface WorkflowTypes {
    // No webhooks found
  }
}
`;
  }

  const workflowTypesEntries = typeBlocks
    .map(
      (b) =>
        `    ${b.name}: {\n      input: ${b.inputType};\n      output: ${b.outputType};\n    };`
    )
    .join('\n');

  const interfaceDefinitions = typeBlocks.map((b) => b.definition).join('\n\n');

  return `// Auto-generated by n8n-connect sync
// Do not edit manually

declare module '@n8n-connect/types' {
  export interface WorkflowTypes {
${workflowTypesEntries}
  }
}

${interfaceDefinitions}
`;
}

interface WebhookInfo {
  workflowId: string;
  workflowName: string;
  path: string;
  method: string;
  node: WebhookNode;
}

function extractWebhooks(workflow: N8nWorkflow): WebhookInfo[] {
  return workflow.nodes.filter(isWebhookNode).map((node) => ({
    workflowId: workflow.id,
    workflowName: workflow.name,
    path: node.parameters.path,
    method: node.parameters.httpMethod ?? 'POST',
    node,
  }));
}

interface TypeBlock {
  name: string;
  inputType: string;
  outputType: string;
  definition: string;
}

function generateWebhookTypes(webhook: WebhookInfo): TypeBlock {
  const safeName = toTypeName(webhook.path);

  return {
    name: `'${webhook.path}'`,
    inputType: `${safeName}Input`,
    outputType: `${safeName}Output`,
    definition: `/**
 * Workflow: ${webhook.workflowName}
 * Path: ${webhook.path}
 * Method: ${webhook.method}
 */
export interface ${safeName}Input {
  // TODO: Define input schema
  [key: string]: unknown;
}

export interface ${safeName}Output {
  // TODO: Define output schema
  [key: string]: unknown;
}`,
  };
}

export function toTypeName(path: string): string {
  return path
    .replace(/^\//, '')
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
    .split('_')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}
